[package]
name = "password-manager"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
hex = "0.4.3"
sha2 = "0.9.8"
aes = "0.7.5"